
  
version: "3.7"

services:
  database: #ESSE É O NOME DO SERVICE QUE DEVE ESTAR NO ARQUIVO DE CRIAÇÃO DE CONEXÃO
    image: redis
    container_name: redis_test
    restart: always
    ports: 
      - 6379:6379
    environment:
      - REDIS_USER=redis
      - REDIS_PASSWORD=teste
      - REDIS_DB=redisTeste
    volumes:
      - redisdata:/data/redis


  app:
    build: .
    container_name: teste-redis
    restart: always
    ports: 
      - 3333:3333
      - 9229:9229 #Você pode inserir essa porta tbm pra poder usar o debug
    volumes: 
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database



volumes:
  redisdata:
    driver: local